# Generated by Django 3.2 on 2021-07-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='testing', max_length=25),
            preserve_default=False,
        ),
    ]
